USE DEV;

DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS (
  SKU_CODE varchar(255) NOT NULL,
  DESCRIPTION varchar(512) DEFAULT NULL,
  SHORT_NAME varchar(100) DEFAULT NULL,
  PRIMARY KEY (SKU_CODE),
  UNIQUE KEY SKU_CODE_UNIQUE (SKU_CODE)
);

DROP TABLE IF EXISTS REGIONS;
CREATE TABLE REGIONS (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ID_UNIQUE (ID)
);

DROP TABLE IF EXISTS REVIEW;
CREATE TABLE REVIEW (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  TITLE varchar(255) DEFAULT NULL,
  RATING int(11) DEFAULT NULL,
  CREATED datetime NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ID_UNIQUE (ID)
);

DROP TABLE IF EXISTS SALES;
CREATE TABLE SALES (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  PRODUCT_SOLD_ID varchar(512) NOT NULL,
  SOLD_PRICE decimal(10,0) NOT NULL,
  TILL_ID varchar(512) NOT NULL,
  SHOP_ID varchar(512) NOT NULL,
  REGION_ID varchar(512) NOT NULL,
  TIME_OF_SALE datetime DEFAULT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS SHOPS;
CREATE TABLE SHOPS (
  ID varchar(512) NOT NULL,
  LOCATION varchar(512) DEFAULT NULL,
  REGION_ID varchar(512) NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TILLS;
CREATE TABLE TILLS (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(512) DEFAULT NULL,
  ATTENDANT varchar(512) DEFAULT NULL,
  LOGIN_TIME datetime DEFAULT NULL,
  LOGOUT_TIME datetime DEFAULT NULL,
  SHOP_ID varchar(512) NOT NULL,
  PRIMARY KEY (ID)
);
